# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'char_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_initial_timetable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initial_timetable.setGeometry(QtCore.QRect(640, 60, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_initial_timetable.setFont(font)
        self.pushButton_initial_timetable.setStyleSheet("background-color: rgb(35, 124, 75);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_initial_timetable.setObjectName("pushButton_initial_timetable")
        self.pushButton_result_timetable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result_timetable.setGeometry(QtCore.QRect(640, 320, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_result_timetable.setFont(font)
        self.pushButton_result_timetable.setStyleSheet("background-color: rgb(35, 124, 75);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_result_timetable.setObjectName("pushButton_result_timetable")
        self.pushButton_lecturer_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lecturer_excel.setGeometry(QtCore.QRect(370, 60, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_lecturer_excel.setFont(font)
        self.pushButton_lecturer_excel.setStyleSheet("background-color: rgb(35, 124, 75);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_lecturer_excel.setObjectName("pushButton_lecturer_excel")
        self.comboBox_lecturer = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_lecturer.setGeometry(QtCore.QRect(200, 180, 161, 41))
        self.comboBox_lecturer.setObjectName("comboBox_lecturer")
        self.comboBox_room = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_room.setGeometry(QtCore.QRect(200, 410, 161, 41))
        self.comboBox_room.setObjectName("comboBox_room")
        self.pushButton_room_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_room_excel.setGeometry(QtCore.QRect(370, 320, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_room_excel.setFont(font)
        self.pushButton_room_excel.setStyleSheet("background-color: rgb(35, 124, 75);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_room_excel.setObjectName("pushButton_room_excel")
        self.label_lecturer_id = QtWidgets.QLabel(self.centralwidget)
        self.label_lecturer_id.setGeometry(QtCore.QRect(200, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_lecturer_id.setFont(font)
        self.label_lecturer_id.setStyleSheet("")
        self.label_lecturer_id.setObjectName("label_lecturer_id")
        self.label_room_id = QtWidgets.QLabel(self.centralwidget)
        self.label_room_id.setGeometry(QtCore.QRect(200, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_room_id.setFont(font)
        self.label_room_id.setObjectName("label_room_id")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(10, 600, 111, 51))
        self.pushButton_back.setObjectName("pushButton_back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1086, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_initial_timetable.setText(_translate("MainWindow", "initial timetable"))
        self.pushButton_result_timetable.setText(_translate("MainWindow", "result timetable"))
        self.pushButton_lecturer_excel.setText(_translate("MainWindow", "lecturer availability excel"))
        self.pushButton_room_excel.setText(_translate("MainWindow", "room availability excel"))
        self.label_lecturer_id.setText(_translate("MainWindow", "lecturer ID"))
        self.label_room_id.setText(_translate("MainWindow", "room ID"))
        self.pushButton_back.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
