# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 713)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 620, 91, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_result_timetable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result_timetable.setGeometry(QtCore.QRect(770, 620, 101, 41))
        self.pushButton_result_timetable.setObjectName("pushButton_result_timetable")
        self.pushButton_initial_timetable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_initial_timetable.setGeometry(QtCore.QRect(610, 620, 101, 41))
        self.pushButton_initial_timetable.setObjectName("pushButton_initial_timetable")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 40, 441, 81))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber_initial_cost = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_initial_cost.setGeometry(QtCore.QRect(40, 10, 81, 41))
        self.lcdNumber_initial_cost.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_initial_cost.setProperty("intValue", 71830)
        self.lcdNumber_initial_cost.setObjectName("lcdNumber_initial_cost")
        self.lcdNumber_final_cost = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_final_cost.setGeometry(QtCore.QRect(40, 130, 81, 41))
        self.lcdNumber_final_cost.setSmallDecimalPoint(False)
        self.lcdNumber_final_cost.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_final_cost.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_final_cost.setProperty("value", 71830.0)
        self.lcdNumber_final_cost.setProperty("intValue", 71830)
        self.lcdNumber_final_cost.setObjectName("lcdNumber_final_cost")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(960, 620, 101, 41))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(860, 30, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:0.479904 rgba(255, 0, 0, 255), stop:0.522685 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_run.setObjectName("pushButton_run")
        self.lcdNumber_final_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_final_temp.setGeometry(QtCore.QRect(40, 70, 81, 41))
        self.lcdNumber_final_temp.setSmallDecimalPoint(False)
        self.lcdNumber_final_temp.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber_final_temp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_final_temp.setProperty("value", 71830.0)
        self.lcdNumber_final_temp.setProperty("intValue", 71830)
        self.lcdNumber_final_temp.setObjectName("lcdNumber_final_temp")
        self.widget_chart_temp = MplWidget(self.centralwidget)
        self.widget_chart_temp.setGeometry(QtCore.QRect(20, 180, 1061, 421))
        self.widget_chart_temp.setObjectName("widget_chart_temp")
        self.label_initial_cost = QtWidgets.QLabel(self.centralwidget)
        self.label_initial_cost.setGeometry(QtCore.QRect(130, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_initial_cost.setFont(font)
        self.label_initial_cost.setObjectName("label_initial_cost")
        self.label__final_temp = QtWidgets.QLabel(self.centralwidget)
        self.label__final_temp.setGeometry(QtCore.QRect(130, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label__final_temp.setFont(font)
        self.label__final_temp.setObjectName("label__final_temp")
        self.label__final_cost = QtWidgets.QLabel(self.centralwidget)
        self.label__final_cost.setGeometry(QtCore.QRect(130, 130, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label__final_cost.setFont(font)
        self.label__final_cost.setObjectName("label__final_cost")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_back.setText(_translate("MainWindow", "BACK"))
        self.pushButton_result_timetable.setText(_translate("MainWindow", "result timetable"))
        self.pushButton_initial_timetable.setText(_translate("MainWindow", "initial timetable"))
        self.pushButton_next.setText(_translate("MainWindow", "next"))
        self.pushButton_run.setText(_translate("MainWindow", "RUN"))
        self.label_initial_cost.setText(_translate("MainWindow", "initial cost function"))
        self.label__final_temp.setText(_translate("MainWindow", "final temperature"))
        self.label__final_cost.setText(_translate("MainWindow", "final cost function"))
from gui.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
